### PR TITLE
Fixup readme badge with badge poser!

### PR DESCRIPTION
**Pull request by JellyBellyDev**
before:
schermata 2018-03-05 alle 15 40 08

after: 
schermata 2018-03-05 alle 15 48 08

### CODE REVIEW

**Comment by nrk** [comment]
shields.io works perfectly fine overall, most likely it was simply a temporary hiccup on their part so I think switching just because of this is kind of overkill TBH.

**Comment by JellyBellyDev** [comment]
I love [Badge Poser](https://poser.pugx.org/), also because it is written in php!
But if you do not want to change, no problem. Close the PR too!
I tried it!

**Comment by drAlberT** [comment]
I had a lot of such issues in the past too with shields.io ...  We could try to change :)

**Comment by nrk** [comment]
@drAlberT the fact is, it's not I have anything against Badge Poser and in the past I was actually [using it in the README](https://github.com/nrk/predis/commit/257791edcfcfee6db3fafb89671d87fb4c9f055b#diff-04c6e90faac2675aa89e2176d2eec7d8), but I switched to **shields.io** because it supports Travis CI and Gitter (and well it even provides an HHVM badge) and I vastly prefer their flat style. Not sure if anything changed about that for Badge Poser...

**Comment by tillkruss** [comment]
Seems to work 👍🏻

**Pull request closed without merging**
