### PR TITLE
Correcting the PHPDocs

### PR DESCRIPTION
**Pull request by felixsand**
Correcting the PHPDocs for bitfield

### CODE REVIEW

**Comment by nrk** [comment]
@felixsand is `$subcommand, ...$subcommandArg` valid phpdoc? Just asking since my phpdoc-fu is not really strong :-) BTW this should also be fixed in [`Predis\ClientContextInterface`](https://github.com/nrk/predis/blob/v1.1/src/ClientContextInterface.php#L41).

**Comment by cebe** [comment]
method definition in phpdoc should be valid PHP, which this would be with php 5.6 http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list

**Comment by nrk** [comment]
@cebe well the last time I used an IDE that supported phpdocs the end result was a bit of a mixed bag, that why I was asking if that signature was properly recognized in annotations despite being valid PHP code :-)

**Comment by cebe** [comment]
before this change, PHPStorm reports syntax error, afterwards its fine. So :+1: from me.

**Comment by nrk** [comment]
@cebe great thanks, I'll merge this PR tomorrow.

**Comment by felixsand** [comment]
Sorry for not responding on time. Was on vacation :-)
Thanks @cebe and @nrk !

**Comment by nrk** [comment]
@felixsand no problem, don't worry and thanks for the fix :)

**Pull request merged**
