### PR TITLE
Added ClusterKeyspace iterator

### PR DESCRIPTION
**Pull request by crispygoth**
This is like the regular Keyspace iterator, but works across all nodes in a Redis Cluster by scanning each node in turn.

### CODE REVIEW

**Comment by lulyon** [comment]
Out of curiosity, What is it for？and what about the performance？

**Comment by nrk** [comment]
@crispygoth honestly I can't see a compelling reason to add a new class at this point when you can compose the very same functionality simply by doing:

```php
foreach ($client as $node) {
    foreach (new \Predis\Collection\Iterator\Keyspace($node) as $key) {
        // DO STUFF
    }
}
```

What's the added benefit of a dedicated iterator?

**Comment by crispygoth** [comment]
Actually, you're right.. I don't even know why that didn't occur to me in the first place! Sorry for the noise, I'll close this PR :)

**Comment by nrk** [comment]
@crispygoth don't worry, thanks for the PR anyway :-)

**Pull request closed without merging**
